(defparameter *irc-host* "irc.nightstar.net")
(defparameter *irc-port* 6667)
(defparameter *cmc-host* "sqweek.dnsdojo.org")
(defparameter *cmc-root* (concatenate 'string *cmc-host* "/cmc/"))
(defparameter *cmc-mmpt* 4171)
(defparameter *cmc-gmpt* 4170)

(defparameter *name* "Caret")
(defparameter *irc-pass* "foo")
(defparameter *cmc-pass* "bar")
